apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-merkleservice
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: {{ include "zkwasm-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: merkleservice
  template:
    metadata:
      labels:
        app: merkleservice
        app.kubernetes.io/name: {{ include "zkwasm-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: merkleservice
        image: "{{ .Values.merkleservice.image.repository }}:{{ .Values.merkleservice.image.tag }}"
        command: ["./target/release/csm_service", "--uri", "mongodb://{{ .Release.Name }}-mongodb:27017"]
        ports:
        - containerPort: {{ .Values.merkleservice.port }}
        env:
        - name: URI
          value: mongodb://{{ .Release.Name }}-mongodb:27017