apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-merkleservice
spec:
  selector:
    matchLabels:
      app: merkleservice
  template:
    metadata:
      labels:
        app: merkleservice
    spec:
      containers:
      - name: merkleservice
        image: "{{ .Values.merkleservice.image.repository }}:{{ .Values.merkleservice.image.tag }}"
        command: ["./target/release/csm_service", "--uri", "mongodb://{{ .Release.Name }}-mongodb:27017"]
        ports:
        - containerPort: {{ .Values.merkleservice.port }}
        env:
        - name: URI
          value: mongodb://{{ .Release.Name }}-mongodb:27017