apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-merkleservice
  labels:
    app.kubernetes.io/name: merkleservice
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: service
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-merkleservice  # 修改这里
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-merkleservice  # 修改这里
        app.kubernetes.io/name: merkleservice
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: service
    spec:
      containers:
      - name: merkleservice
        image: "{{ .Values.merkleservice.image.repository }}:{{ .Values.merkleservice.image.tag }}"
        command: 
          - "./target/release/csm_service"
          - "--uri"
          - "mongodb://{{ .Release.Name }}-mongodb:{{ .Values.mongodb.port }}"
        ports:
        - containerPort: {{ .Values.merkleservice.port }}
          name: http
        env:
        - name: URI
          value: "mongodb://{{ .Release.Name }}-mongodb:{{ .Values.mongodb.port }}"