apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongodb-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-disk
  csi:
    driver: disk.csi.everest.io
    fsType: ext4
    volumeHandle: {{ .Values.mongodb.persistence.volumeHandle }}
    volumeAttributes:
      storage.kubernetes.io/csi-provisioner-identity: everest-csi-provisioner 