apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongodb-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mongodb-{{ .Release.Name }}  # 为每个实例使用唯一的目录
    type: DirectoryOrCreate 