apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb  # 修改这里
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb  # 修改这里
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database
    spec:
      initContainers:
      - name: remove-lock
        image: busybox
        command: ['sh', '-c', 'rm -f /data/db/mongod.lock']
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongodb-pvc