apiVersion: v1
kind: Service
metadata:
  name: merkleservice
spec:
  selector:
    app: merkleservice
  ports:
  - port: {{ .Values.merkleservice.port }}
    targetPort: {{ .Values.merkleservice.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}

    